
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/elixxir/client/bindings
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bindings_FRAMEWORK_H__
#define __Bindings_FRAMEWORK_H__

#include "Bindings.objc.h"
#include "Universe.objc.h"

#endif
